### ISSUE TITLE
Mkdir -p functionality

### ISSUE THREAD

**Issue by vbudhram** [RiptideCloud/s3fs#11]
Hey guys what do you think about adding the functionality for mkdir -p (recursive directory creation) to S3FS? Currently, the NodeJS FS implementation does not have this ability.

I could add it for S3 and FS file systems.

**Comment by DavidTPate** [comment]
So we actually have this already implemented through our [FS Mixins](https://github.com/RiptideCloud/node-fs-wishlist) which can be used for S3FS/FS/FSP/etc. to achieve making the directories recursively. As for S3FS this shouldn't really matter since S3 doesn't consider a folder to be an object. So if you create something in a directory that doesn't exist it will just make it there no problem.

I'm planning on implementing a simple `mkdirp` for S3FS once I get some time since it would just need to make one call non-recursively to create all the directories.

**Comment by vbudhram** [comment]
Cool, that is exactly what I needed
